[theme]
primaryColor = "#58a6ff"
backgroundColor = "#0a0e14"
secondaryBackgroundColor = "#0d1117"
textColor = "#e6edf3"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
